### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ChinVision** [alekswebnet/vue-quilly#4]
please embedding a plugin named "quill image resize" plugin,  thanks.
when i use VUE3 and Vite build the project, i got a error....other plugin can't use

**Comment by alekswebnet** [comment]
@ChinVision It is possible, but with some tweaks, because the plugin supports Quill v1. Please run https://vue-quilly.vercel.app/#tab=image-resize and see https://github.com/alekswebnet/vue-quilly/blob/main/demo/src/components/ImageResizeEditor.vue

**Comment by ChinVision** [comment]
it's work! thanks!

**Comment by alekswebnet** [comment]
It's just a "quick fix" solution. It would be much better to upgrade `quill-image-resize-module` to make it compatible with Quill 2 https://github.com/kensnyder/quill-image-resize-module/issues/156
